### ISSUE TITLE
I/O Error when trying to run a benchmark on a FMX Forms project on Windows

### ISSUE THREAD

**Issue by YerayAlonso** [spring4d/benchmark#2]
If I create a Console application, I can run benchmarks on Windows 32/64 platforms.
However, if I try to create a "Multi-Device Application - Delphi", when I run a benchmark on Windows 32/64 platforms I get this error message:

> Project FMXBenchmarkForm.exe raised exception class EInOutError with message 'I/O error 105'.

![imagen](https://user-images.githubusercontent.com/1788228/144421189-69a18660-c46a-448d-8c3a-b1c115466fe8.png)

It seems to fail to initialize the console (`displayReporter`) as output for the report here:
```delphi
  if displayReporter.ReportContext(context) and
    ((fileReporter = nil) or fileReporter.ReportContext(context)) then
```

**Comment by sglienke** [comment]
An I/O Error happens when doing a Writeln without being a console application or having console output allocated.
That is because you did not create a console application - you can however fix it by calling AllocConsole on Windows - for other platforms I don't know the exact function for that.
