### ISSUE TITLE
VCL

### ISSUE THREAD

**Issue by BoscoBecker** [spring4d/benchmark#5]
Don't work in VCL

**Comment by sglienke** [comment]
Is it too much to ask for more details?

**Comment by BoscoBecker** [comment]
Sure, why not?

I do the same example on the benchmark page, but a get error.

![image](https://github.com/user-attachments/assets/3af50ea9-e6c3-494d-be0e-4a2ecf27f00a)

_E2009 Incompatible types: 'regular procedure and method pointer'_ 


After a while I managed to run the example.

Actually it was because I needed a user class procedure, not a simple procedure or function.


``` pascal
class procedure TForm3.BM_SomeFunction(const state: TState);
begin
  // Perform setup here
  for var _ in state do
  begin
    GetTest;
  end;
end;

procedure TForm3.Button1Click(Sender: TObject);
begin
  // Register the function as a benchmark
  Benchmark(BM_SomeFunction, 'GetTest');
  // Run the benchmark
  Benchmark_Main;
end;

class procedure TForm3.GetTest;
begin
   sleep(2000);
end;
``` 

But, yet a have erro

![image](https://github.com/user-attachments/assets/bf56f004-8ef9-4c73-9e20-82fe958b92ab)


It could have examples, it would be good. :)

**Comment by sglienke** [comment]
- The benchmark function has to be a `procedure(const state: TState)` you are providing a method - they are incompatible. This has nothing to do with VCL. You might want to read up on them [in the documentation](https://docwiki.embarcadero.com/RADStudio/Alexandria/en/Procedural_Types_(Delphi))
- The IO error is a result of calling `Write` from a VCL application

Benchmark is meant to run as a console application - there is no point on running this inside a VCL application.
